version: '2'

networks:
  default:
    driver: bridge

services:
  nextcloud:
    image: wonderfall/nextcloud
    links:
      - nextcloud-db:nextcloud-db   # If using MySQL
      - solr:solr                   # If using Nextant
      - redis:redis                 # If using Redis
  #depends_on:
  #    - nextcloud-db           # If using MySQL
  #    - solr                   # If using Nextant
  #    - redis                  # If using Redis
    environment:
      - UID=1000
      - GID=1000
      - UPLOAD_MAX_SIZE=10G
      - APC_SHM_SIZE=128M
      - OPCACHE_MEM_SIZE=128
      - CRON_PERIOD=15m
      - TZ=Asia/Shanghai
      - ADMIN_USER=admin            # Don't set to configure through browser
      - ADMIN_PASSWORD=admin        # Don't set to configure through browser
      - DOMAIN=localhost
      - DB_TYPE=mysql
      - DB_NAME=nextcloud
      - DB_USER=nextcloud
      - DB_PASSWORD=1234567890abc
      - DB_HOST=nextcloud-db
    volumes:
      - /data:/data
      - /config:/config
      - /apps:/apps2
      - /themes:/nextcloud/themes
    ports:
      - "8888:80"


  # If using MySQL
  nextcloud-db:
    image: mariadb:10
    volumes:
      - /db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234567890abc
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=1234567890abc


  # If using Nextant
  solr:
    image: solr:6-alpine
    container_name: solr
    volumes:
      - /solr:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - nextant

      
  # If using Redis
  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - /redis:/data
